### ISSUE TITLE
Transtats link is bad

### ISSUE THREAD

**Issue by 3vivekb** [vta/Data-Gathering#27]
This link:
http://www.transtats.bts.gov/FieldInfo.asp?Field_Desc=Service%20Availability%20Indicator%20for%20Transit%20Bus&Field_Type=Num&Lookup_Table=L_TRANSNET_FACILITY_AVAIL&Table_ID=1180&SYS_Table_Name=T_TRANSNET_FACILITY&Sys_Field_Name=BUS_TRANSIT

isn't helpful.

**Comment by phuuuuungus** [comment]
Removed

**Comment by 3vivekb** [comment]
Maybe don't remove this but correct it?  The data can be good but the link to the data isn't.  Maybe document how to get to the data.

**Comment by 3vivekb** [comment]
https://github.com/vta/Data-Gathering/commit/3e6775e736e64d76da997cf78e9ea936e767cb6e

Need to add transstats back @nliu83

**Comment by nliu83** [comment]
for the transtat data, do you mean to document data within the site?

**Comment by 3vivekb** [comment]
Yea.  Anything.
