### ISSUE TITLE
Data Sources - PDF's aren't really sources

### ISSUE THREAD

**Issue by SJClaus** [vta/Data-Gathering#8]
Natalie, the data you added to the data.csv file is a PDF. There's no way to extract that data other than to read the PDF, therefore it's not going to be useful. Can you please find sources where we could actually download the raw data from?

**Comment by nliu83** [comment]
A lot of the information I am finding are PDFs, but i'll look for more sources.

**Comment by 3vivekb** [comment]
A PDF is stll a data source. Just make it clear that is a pdf.  Then the VTA and the public can push those organizations to make better data available.

Data takes all forms.  The point of our research is to find as many possible sources as we can.

**Comment by SJClaus** [comment]
Good point, thank you for the clarification.
